require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DutiesController do

  # This should return the minimal set of attributes required to create a valid
  # Duty. As you add validations to Duty, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DutiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all duties as @duties" do
      duty = Duty.create! valid_attributes
      get :index, {}, valid_session
      assigns(:duties).should eq([duty])
    end
  end

  describe "GET show" do
    it "assigns the requested duty as @duty" do
      duty = Duty.create! valid_attributes
      get :show, {:id => duty.to_param}, valid_session
      assigns(:duty).should eq(duty)
    end
  end

  describe "GET new" do
    it "assigns a new duty as @duty" do
      get :new, {}, valid_session
      assigns(:duty).should be_a_new(Duty)
    end
  end

  describe "GET edit" do
    it "assigns the requested duty as @duty" do
      duty = Duty.create! valid_attributes
      get :edit, {:id => duty.to_param}, valid_session
      assigns(:duty).should eq(duty)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Duty" do
        expect {
          post :create, {:duty => valid_attributes}, valid_session
        }.to change(Duty, :count).by(1)
      end

      it "assigns a newly created duty as @duty" do
        post :create, {:duty => valid_attributes}, valid_session
        assigns(:duty).should be_a(Duty)
        assigns(:duty).should be_persisted
      end

      it "redirects to the created duty" do
        post :create, {:duty => valid_attributes}, valid_session
        response.should redirect_to(Duty.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved duty as @duty" do
        # Trigger the behavior that occurs when invalid params are submitted
        Duty.any_instance.stub(:save).and_return(false)
        post :create, {:duty => {}}, valid_session
        assigns(:duty).should be_a_new(Duty)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Duty.any_instance.stub(:save).and_return(false)
        post :create, {:duty => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested duty" do
        duty = Duty.create! valid_attributes
        # Assuming there are no other duties in the database, this
        # specifies that the Duty created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Duty.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => duty.to_param, :duty => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested duty as @duty" do
        duty = Duty.create! valid_attributes
        put :update, {:id => duty.to_param, :duty => valid_attributes}, valid_session
        assigns(:duty).should eq(duty)
      end

      it "redirects to the duty" do
        duty = Duty.create! valid_attributes
        put :update, {:id => duty.to_param, :duty => valid_attributes}, valid_session
        response.should redirect_to(duty)
      end
    end

    describe "with invalid params" do
      it "assigns the duty as @duty" do
        duty = Duty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Duty.any_instance.stub(:save).and_return(false)
        put :update, {:id => duty.to_param, :duty => {}}, valid_session
        assigns(:duty).should eq(duty)
      end

      it "re-renders the 'edit' template" do
        duty = Duty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Duty.any_instance.stub(:save).and_return(false)
        put :update, {:id => duty.to_param, :duty => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested duty" do
      duty = Duty.create! valid_attributes
      expect {
        delete :destroy, {:id => duty.to_param}, valid_session
      }.to change(Duty, :count).by(-1)
    end

    it "redirects to the duties list" do
      duty = Duty.create! valid_attributes
      delete :destroy, {:id => duty.to_param}, valid_session
      response.should redirect_to(duties_url)
    end
  end

end
