require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RentDocumentsController do

  # This should return the minimal set of attributes required to create a valid
  # RentDocument. As you add validations to RentDocument, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RentDocumentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all rent_documents as @rent_documents" do
      rent_document = RentDocument.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rent_documents).should eq([rent_document])
    end
  end

  describe "GET show" do
    it "assigns the requested rent_document as @rent_document" do
      rent_document = RentDocument.create! valid_attributes
      get :show, {:id => rent_document.to_param}, valid_session
      assigns(:rent_document).should eq(rent_document)
    end
  end

  describe "GET new" do
    it "assigns a new rent_document as @rent_document" do
      get :new, {}, valid_session
      assigns(:rent_document).should be_a_new(RentDocument)
    end
  end

  describe "GET edit" do
    it "assigns the requested rent_document as @rent_document" do
      rent_document = RentDocument.create! valid_attributes
      get :edit, {:id => rent_document.to_param}, valid_session
      assigns(:rent_document).should eq(rent_document)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RentDocument" do
        expect {
          post :create, {:rent_document => valid_attributes}, valid_session
        }.to change(RentDocument, :count).by(1)
      end

      it "assigns a newly created rent_document as @rent_document" do
        post :create, {:rent_document => valid_attributes}, valid_session
        assigns(:rent_document).should be_a(RentDocument)
        assigns(:rent_document).should be_persisted
      end

      it "redirects to the created rent_document" do
        post :create, {:rent_document => valid_attributes}, valid_session
        response.should redirect_to(RentDocument.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rent_document as @rent_document" do
        # Trigger the behavior that occurs when invalid params are submitted
        RentDocument.any_instance.stub(:save).and_return(false)
        post :create, {:rent_document => {}}, valid_session
        assigns(:rent_document).should be_a_new(RentDocument)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RentDocument.any_instance.stub(:save).and_return(false)
        post :create, {:rent_document => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rent_document" do
        rent_document = RentDocument.create! valid_attributes
        # Assuming there are no other rent_documents in the database, this
        # specifies that the RentDocument created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RentDocument.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => rent_document.to_param, :rent_document => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested rent_document as @rent_document" do
        rent_document = RentDocument.create! valid_attributes
        put :update, {:id => rent_document.to_param, :rent_document => valid_attributes}, valid_session
        assigns(:rent_document).should eq(rent_document)
      end

      it "redirects to the rent_document" do
        rent_document = RentDocument.create! valid_attributes
        put :update, {:id => rent_document.to_param, :rent_document => valid_attributes}, valid_session
        response.should redirect_to(rent_document)
      end
    end

    describe "with invalid params" do
      it "assigns the rent_document as @rent_document" do
        rent_document = RentDocument.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RentDocument.any_instance.stub(:save).and_return(false)
        put :update, {:id => rent_document.to_param, :rent_document => {}}, valid_session
        assigns(:rent_document).should eq(rent_document)
      end

      it "re-renders the 'edit' template" do
        rent_document = RentDocument.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RentDocument.any_instance.stub(:save).and_return(false)
        put :update, {:id => rent_document.to_param, :rent_document => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rent_document" do
      rent_document = RentDocument.create! valid_attributes
      expect {
        delete :destroy, {:id => rent_document.to_param}, valid_session
      }.to change(RentDocument, :count).by(-1)
    end

    it "redirects to the rent_documents list" do
      rent_document = RentDocument.create! valid_attributes
      delete :destroy, {:id => rent_document.to_param}, valid_session
      response.should redirect_to(rent_documents_url)
    end
  end

end
